//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Договор.
    /// </summary>
    //  *** Start programmer edit section *** (Договор CustomAttributes)

    //  *** End programmer edit section *** (Договор CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоговорE", new string[0])]
    [View("ДоговорL", new string[0])]
    public class Договор : ICSSoft.STORMNET.DataObject
    {
        
        private int fИдентификатор;
        
        private System.Guid fprimarykey;
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаОкончания;
        
        private string fСостояние;
        
        private IIS.project2.DetailArrayOfЗУДоговора fЗУДоговора;
        
        private IIS.project2.DetailArrayOfКонтрДоговора fКонтрДоговора;
        
        //  *** Start programmer edit section *** (Договор CustomMembers)

        //  *** End programmer edit section *** (Договор CustomMembers)

        
        /// <summary>
        /// Идентификатор.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.Идентификатор CustomAttributes)

        //  *** End programmer edit section *** (Договор.Идентификатор CustomAttributes)
        public virtual int Идентификатор
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.Идентификатор Get start)

                //  *** End programmer edit section *** (Договор.Идентификатор Get start)
                int result = this.fИдентификатор;
                //  *** Start programmer edit section *** (Договор.Идентификатор Get end)

                //  *** End programmer edit section *** (Договор.Идентификатор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.Идентификатор Set start)

                //  *** End programmer edit section *** (Договор.Идентификатор Set start)
                this.fИдентификатор = value;
                //  *** Start programmer edit section *** (Договор.Идентификатор Set end)

                //  *** End programmer edit section *** (Договор.Идентификатор Set end)
            }
        }
        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.primarykey CustomAttributes)

        //  *** End programmer edit section *** (Договор.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.primarykey Get start)

                //  *** End programmer edit section *** (Договор.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (Договор.primarykey Get end)

                //  *** End programmer edit section *** (Договор.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.primarykey Set start)

                //  *** End programmer edit section *** (Договор.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (Договор.primarykey Set end)

                //  *** End programmer edit section *** (Договор.primarykey Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.ДатаНачала CustomAttributes)

        //  *** End programmer edit section *** (Договор.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.ДатаНачала Get start)

                //  *** End programmer edit section *** (Договор.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                //  *** Start programmer edit section *** (Договор.ДатаНачала Get end)

                //  *** End programmer edit section *** (Договор.ДатаНачала Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.ДатаНачала Set start)

                //  *** End programmer edit section *** (Договор.ДатаНачала Set start)
                this.fДатаНачала = value;
                //  *** Start programmer edit section *** (Договор.ДатаНачала Set end)

                //  *** End programmer edit section *** (Договор.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.ДатаОкончания CustomAttributes)

        //  *** End programmer edit section *** (Договор.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.ДатаОкончания Get start)

                //  *** End programmer edit section *** (Договор.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                //  *** Start programmer edit section *** (Договор.ДатаОкончания Get end)

                //  *** End programmer edit section *** (Договор.ДатаОкончания Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.ДатаОкончания Set start)

                //  *** End programmer edit section *** (Договор.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                //  *** Start programmer edit section *** (Договор.ДатаОкончания Set end)

                //  *** End programmer edit section *** (Договор.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.Состояние CustomAttributes)

        //  *** End programmer edit section *** (Договор.Состояние CustomAttributes)
        [StrLen(255)]
        public virtual string Состояние
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.Состояние Get start)

                //  *** End programmer edit section *** (Договор.Состояние Get start)
                string result = this.fСостояние;
                //  *** Start programmer edit section *** (Договор.Состояние Get end)

                //  *** End programmer edit section *** (Договор.Состояние Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.Состояние Set start)

                //  *** End programmer edit section *** (Договор.Состояние Set start)
                this.fСостояние = value;
                //  *** Start programmer edit section *** (Договор.Состояние Set end)

                //  *** End programmer edit section *** (Договор.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Договор.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.ЗУДоговора CustomAttributes)

        //  *** End programmer edit section *** (Договор.ЗУДоговора CustomAttributes)
        public virtual IIS.project2.DetailArrayOfЗУДоговора ЗУДоговора
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.ЗУДоговора Get start)

                //  *** End programmer edit section *** (Договор.ЗУДоговора Get start)
                if ((this.fЗУДоговора == null))
                {
                    this.fЗУДоговора = new IIS.project2.DetailArrayOfЗУДоговора(this);
                }
                IIS.project2.DetailArrayOfЗУДоговора result = this.fЗУДоговора;
                //  *** Start programmer edit section *** (Договор.ЗУДоговора Get end)

                //  *** End programmer edit section *** (Договор.ЗУДоговора Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.ЗУДоговора Set start)

                //  *** End programmer edit section *** (Договор.ЗУДоговора Set start)
                this.fЗУДоговора = value;
                //  *** Start programmer edit section *** (Договор.ЗУДоговора Set end)

                //  *** End programmer edit section *** (Договор.ЗУДоговора Set end)
            }
        }
        
        /// <summary>
        /// Договор.
        /// </summary>
        //  *** Start programmer edit section *** (Договор.КонтрДоговора CustomAttributes)

        //  *** End programmer edit section *** (Договор.КонтрДоговора CustomAttributes)
        public virtual IIS.project2.DetailArrayOfКонтрДоговора КонтрДоговора
        {
            get
            {
                //  *** Start programmer edit section *** (Договор.КонтрДоговора Get start)

                //  *** End programmer edit section *** (Договор.КонтрДоговора Get start)
                if ((this.fКонтрДоговора == null))
                {
                    this.fКонтрДоговора = new IIS.project2.DetailArrayOfКонтрДоговора(this);
                }
                IIS.project2.DetailArrayOfКонтрДоговора result = this.fКонтрДоговора;
                //  *** Start programmer edit section *** (Договор.КонтрДоговора Get end)

                //  *** End programmer edit section *** (Договор.КонтрДоговора Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Договор.КонтрДоговора Set start)

                //  *** End programmer edit section *** (Договор.КонтрДоговора Set start)
                this.fКонтрДоговора = value;
                //  *** Start programmer edit section *** (Договор.КонтрДоговора Set end)

                //  *** End programmer edit section *** (Договор.КонтрДоговора Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоговорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорE", typeof(IIS.project2.Договор));
                }
            }
            
            /// <summary>
            /// "ДоговорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорL", typeof(IIS.project2.Договор));
                }
            }
        }
    }
}
