//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Земельный участок.
    /// </summary>
    //  *** Start programmer edit section *** (ЗУ CustomAttributes)

    //  *** End programmer edit section *** (ЗУ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗемельныйУчастокE", new string[] {
            "primarykey as \'Primarykey\'"})]
    [View("ЗемельныйУчастокL", new string[] {
            "primarykey as \'Primarykey\'"})]
    [View("ЗУE", new string[] {
            "primarykey as \'Primarykey\'",
            "КадНомер as \'Кад номер\'",
            "Адрес as \'Адрес\'",
            "РазрИсп as \'Разр исп\'"})]
    [View("ЗУL", new string[] {
            "primarykey as \'Primarykey\'",
            "КадНомер as \'Кад номер\'",
            "Адрес as \'Адрес\'",
            "РазрИсп as \'Разр исп\'"})]
    public class ЗУ : ICSSoft.STORMNET.DataObject
    {
        
        private System.Guid fprimarykey;
        
        private string fКадНомер;
        
        private string fАдрес;
        
        private string fРазрИсп;
        
        //  *** Start programmer edit section *** (ЗУ CustomMembers)

        //  *** End programmer edit section *** (ЗУ CustomMembers)

        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУ.primarykey CustomAttributes)

        //  *** End programmer edit section *** (ЗУ.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУ.primarykey Get start)

                //  *** End programmer edit section *** (ЗУ.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (ЗУ.primarykey Get end)

                //  *** End programmer edit section *** (ЗУ.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУ.primarykey Set start)

                //  *** End programmer edit section *** (ЗУ.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (ЗУ.primarykey Set end)

                //  *** End programmer edit section *** (ЗУ.primarykey Set end)
            }
        }
        
        /// <summary>
        /// КадНомер.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУ.КадНомер CustomAttributes)

        //  *** End programmer edit section *** (ЗУ.КадНомер CustomAttributes)
        [StrLen(255)]
        public virtual string КадНомер
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУ.КадНомер Get start)

                //  *** End programmer edit section *** (ЗУ.КадНомер Get start)
                string result = this.fКадНомер;
                //  *** Start programmer edit section *** (ЗУ.КадНомер Get end)

                //  *** End programmer edit section *** (ЗУ.КадНомер Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУ.КадНомер Set start)

                //  *** End programmer edit section *** (ЗУ.КадНомер Set start)
                this.fКадНомер = value;
                //  *** Start programmer edit section *** (ЗУ.КадНомер Set end)

                //  *** End programmer edit section *** (ЗУ.КадНомер Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУ.Адрес CustomAttributes)

        //  *** End programmer edit section *** (ЗУ.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУ.Адрес Get start)

                //  *** End programmer edit section *** (ЗУ.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (ЗУ.Адрес Get end)

                //  *** End programmer edit section *** (ЗУ.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУ.Адрес Set start)

                //  *** End programmer edit section *** (ЗУ.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (ЗУ.Адрес Set end)

                //  *** End programmer edit section *** (ЗУ.Адрес Set end)
            }
        }
        
        /// <summary>
        /// РазрИсп.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУ.РазрИсп CustomAttributes)

        //  *** End programmer edit section *** (ЗУ.РазрИсп CustomAttributes)
        [StrLen(255)]
        public virtual string РазрИсп
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУ.РазрИсп Get start)

                //  *** End programmer edit section *** (ЗУ.РазрИсп Get start)
                string result = this.fРазрИсп;
                //  *** Start programmer edit section *** (ЗУ.РазрИсп Get end)

                //  *** End programmer edit section *** (ЗУ.РазрИсп Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУ.РазрИсп Set start)

                //  *** End programmer edit section *** (ЗУ.РазрИсп Set start)
                this.fРазрИсп = value;
                //  *** Start programmer edit section *** (ЗУ.РазрИсп Set end)

                //  *** End programmer edit section *** (ЗУ.РазрИсп Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗемельныйУчастокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗемельныйУчастокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗемельныйУчастокE", typeof(IIS.project2.ЗУ));
                }
            }
            
            /// <summary>
            /// "ЗемельныйУчастокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗемельныйУчастокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗемельныйУчастокL", typeof(IIS.project2.ЗУ));
                }
            }
            
            /// <summary>
            /// "ЗУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗУE", typeof(IIS.project2.ЗУ));
                }
            }
            
            /// <summary>
            /// "ЗУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗУL", typeof(IIS.project2.ЗУ));
                }
            }
        }
    }
}
