//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// З у договора.
    /// </summary>
    //  *** Start programmer edit section *** (ЗУДоговора CustomAttributes)

    //  *** End programmer edit section *** (ЗУДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("З у договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗУДоговораE", new string[0])]
    [View("ЗУДоговораL", new string[0])]
    public class ЗУДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private System.Guid fprimarykey;
        
        private IIS.project2.ЗУ fЗУ;
        
        private IIS.project2.Договор fДоговор;
        
        //  *** Start programmer edit section *** (ЗУДоговора CustomMembers)

        //  *** End programmer edit section *** (ЗУДоговора CustomMembers)

        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУДоговора.primarykey CustomAttributes)

        //  *** End programmer edit section *** (ЗУДоговора.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУДоговора.primarykey Get start)

                //  *** End programmer edit section *** (ЗУДоговора.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (ЗУДоговора.primarykey Get end)

                //  *** End programmer edit section *** (ЗУДоговора.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУДоговора.primarykey Set start)

                //  *** End programmer edit section *** (ЗУДоговора.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (ЗУДоговора.primarykey Set end)

                //  *** End programmer edit section *** (ЗУДоговора.primarykey Set end)
            }
        }
        
        /// <summary>
        /// З у договора.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУДоговора.ЗУ CustomAttributes)

        //  *** End programmer edit section *** (ЗУДоговора.ЗУ CustomAttributes)
        [NotNull()]
        public virtual IIS.project2.ЗУ ЗУ
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУДоговора.ЗУ Get start)

                //  *** End programmer edit section *** (ЗУДоговора.ЗУ Get start)
                IIS.project2.ЗУ result = this.fЗУ;
                //  *** Start programmer edit section *** (ЗУДоговора.ЗУ Get end)

                //  *** End programmer edit section *** (ЗУДоговора.ЗУ Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУДоговора.ЗУ Set start)

                //  *** End programmer edit section *** (ЗУДоговора.ЗУ Set start)
                this.fЗУ = value;
                //  *** Start programmer edit section *** (ЗУДоговора.ЗУ Set end)

                //  *** End programmer edit section *** (ЗУДоговора.ЗУ Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.project2.Договор.
        /// </summary>
        //  *** Start programmer edit section *** (ЗУДоговора.Договор CustomAttributes)

        //  *** End programmer edit section *** (ЗУДоговора.Договор CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.project2.Договор Договор
        {
            get
            {
                //  *** Start programmer edit section *** (ЗУДоговора.Договор Get start)

                //  *** End programmer edit section *** (ЗУДоговора.Договор Get start)
                IIS.project2.Договор result = this.fДоговор;
                //  *** Start programmer edit section *** (ЗУДоговора.Договор Get end)

                //  *** End programmer edit section *** (ЗУДоговора.Договор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗУДоговора.Договор Set start)

                //  *** End programmer edit section *** (ЗУДоговора.Договор Set start)
                this.fДоговор = value;
                //  *** Start programmer edit section *** (ЗУДоговора.Договор Set end)

                //  *** End programmer edit section *** (ЗУДоговора.Договор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗУДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗУДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗУДоговораE", typeof(IIS.project2.ЗУДоговора));
                }
            }
            
            /// <summary>
            /// "ЗУДоговораL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗУДоговораL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗУДоговораL", typeof(IIS.project2.ЗУДоговора));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗУДоговора.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfЗУДоговора CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfЗУДоговора CustomAttributes)
    public class DetailArrayOfЗУДоговора : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.project2.DetailArrayOfЗУДоговора members)

        //  *** End programmer edit section *** (IIS.project2.DetailArrayOfЗУДоговора members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗУДоговора by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗУДоговора.
        /// </summary>
        public DetailArrayOfЗУДоговора(IIS.project2.Договор fДоговор) : 
                base(typeof(ЗУДоговора), ((ICSSoft.STORMNET.DataObject)(fДоговор)))
        {
        }
        
        public IIS.project2.ЗУДоговора this[int index]
        {
            get
            {
                return ((IIS.project2.ЗУДоговора)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.project2.ЗУДоговора dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
