//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контр договора.
    /// </summary>
    //  *** Start programmer edit section *** (КонтрДоговора CustomAttributes)

    //  *** End programmer edit section *** (КонтрДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("Контр договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтрДоговораE", new string[] {
            "primarykey as \'Primarykey\'",
            "Контрагент as \'Контрагент\'",
            "Контрагент.Тип as \'Тип\'"}, Hidden=new string[] {
            "Контрагент.Тип"})]
    [MasterViewDefineAttribute("КонтрДоговораE", "Контрагент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Тип")]
    public class КонтрДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private System.Guid fprimarykey;
        
        private IIS.project2.Контрагент fКонтрагент;
        
        private IIS.project2.Договор fДоговор;
        
        //  *** Start programmer edit section *** (КонтрДоговора CustomMembers)

        //  *** End programmer edit section *** (КонтрДоговора CustomMembers)

        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (КонтрДоговора.primarykey CustomAttributes)

        //  *** End programmer edit section *** (КонтрДоговора.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (КонтрДоговора.primarykey Get start)

                //  *** End programmer edit section *** (КонтрДоговора.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (КонтрДоговора.primarykey Get end)

                //  *** End programmer edit section *** (КонтрДоговора.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (КонтрДоговора.primarykey Set start)

                //  *** End programmer edit section *** (КонтрДоговора.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (КонтрДоговора.primarykey Set end)

                //  *** End programmer edit section *** (КонтрДоговора.primarykey Set end)
            }
        }
        
        /// <summary>
        /// Контр договора.
        /// </summary>
        //  *** Start programmer edit section *** (КонтрДоговора.Контрагент CustomAttributes)

        //  *** End programmer edit section *** (КонтрДоговора.Контрагент CustomAttributes)
        [NotNull()]
        public virtual IIS.project2.Контрагент Контрагент
        {
            get
            {
                //  *** Start programmer edit section *** (КонтрДоговора.Контрагент Get start)

                //  *** End programmer edit section *** (КонтрДоговора.Контрагент Get start)
                IIS.project2.Контрагент result = this.fКонтрагент;
                //  *** Start programmer edit section *** (КонтрДоговора.Контрагент Get end)

                //  *** End programmer edit section *** (КонтрДоговора.Контрагент Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (КонтрДоговора.Контрагент Set start)

                //  *** End programmer edit section *** (КонтрДоговора.Контрагент Set start)
                this.fКонтрагент = value;
                //  *** Start programmer edit section *** (КонтрДоговора.Контрагент Set end)

                //  *** End programmer edit section *** (КонтрДоговора.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.project2.Договор.
        /// </summary>
        //  *** Start programmer edit section *** (КонтрДоговора.Договор CustomAttributes)

        //  *** End programmer edit section *** (КонтрДоговора.Договор CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.project2.Договор Договор
        {
            get
            {
                //  *** Start programmer edit section *** (КонтрДоговора.Договор Get start)

                //  *** End programmer edit section *** (КонтрДоговора.Договор Get start)
                IIS.project2.Договор result = this.fДоговор;
                //  *** Start programmer edit section *** (КонтрДоговора.Договор Get end)

                //  *** End programmer edit section *** (КонтрДоговора.Договор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (КонтрДоговора.Договор Set start)

                //  *** End programmer edit section *** (КонтрДоговора.Договор Set start)
                this.fДоговор = value;
                //  *** Start programmer edit section *** (КонтрДоговора.Договор Set end)

                //  *** End programmer edit section *** (КонтрДоговора.Договор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтрДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрДоговораE", typeof(IIS.project2.КонтрДоговора));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of КонтрДоговора.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfКонтрДоговора CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfКонтрДоговора CustomAttributes)
    public class DetailArrayOfКонтрДоговора : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.project2.DetailArrayOfКонтрДоговора members)

        //  *** End programmer edit section *** (IIS.project2.DetailArrayOfКонтрДоговора members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type КонтрДоговора by index.
        /// </summary>
        /// <summary>
        /// Adds object with type КонтрДоговора.
        /// </summary>
        public DetailArrayOfКонтрДоговора(IIS.project2.Договор fДоговор) : 
                base(typeof(КонтрДоговора), ((ICSSoft.STORMNET.DataObject)(fДоговор)))
        {
        }
        
        public IIS.project2.КонтрДоговора this[int index]
        {
            get
            {
                return ((IIS.project2.КонтрДоговора)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.project2.КонтрДоговора dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
