//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контрагент.
    /// </summary>
    //  *** Start programmer edit section *** (Контрагент CustomAttributes)

    //  *** End programmer edit section *** (Контрагент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтрагентE", new string[] {
            "primarykey as \'Primarykey\'",
            "Тип as \'Тип\'",
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "ОГРН as \'ОГРН\'"})]
    [View("КонтрагентL", new string[] {
            "primarykey as \'Primarykey\'",
            "Тип as \'Тип\'",
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "ОГРН as \'ОГРН\'"})]
    public class Контрагент : ICSSoft.STORMNET.DataObject
    {
        
        private System.Guid fprimarykey;
        
        private string fТип;
        
        private string fНаименование;
        
        private string fИНН;
        
        private string fОГРН;
        
        //  *** Start programmer edit section *** (Контрагент CustomMembers)

        //  *** End programmer edit section *** (Контрагент CustomMembers)

        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (Контрагент.primarykey CustomAttributes)

        //  *** End programmer edit section *** (Контрагент.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (Контрагент.primarykey Get start)

                //  *** End programmer edit section *** (Контрагент.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (Контрагент.primarykey Get end)

                //  *** End programmer edit section *** (Контрагент.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Контрагент.primarykey Set start)

                //  *** End programmer edit section *** (Контрагент.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (Контрагент.primarykey Set end)

                //  *** End programmer edit section *** (Контрагент.primarykey Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        //  *** Start programmer edit section *** (Контрагент.Тип CustomAttributes)

        //  *** End programmer edit section *** (Контрагент.Тип CustomAttributes)
        [StrLen(255)]
        public virtual string Тип
        {
            get
            {
                //  *** Start programmer edit section *** (Контрагент.Тип Get start)

                //  *** End programmer edit section *** (Контрагент.Тип Get start)
                string result = this.fТип;
                //  *** Start programmer edit section *** (Контрагент.Тип Get end)

                //  *** End programmer edit section *** (Контрагент.Тип Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Контрагент.Тип Set start)

                //  *** End programmer edit section *** (Контрагент.Тип Set start)
                this.fТип = value;
                //  *** Start programmer edit section *** (Контрагент.Тип Set end)

                //  *** End programmer edit section *** (Контрагент.Тип Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Контрагент.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Контрагент.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Контрагент.Наименование Get start)

                //  *** End programmer edit section *** (Контрагент.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Контрагент.Наименование Get end)

                //  *** End programmer edit section *** (Контрагент.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Контрагент.Наименование Set start)

                //  *** End programmer edit section *** (Контрагент.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Контрагент.Наименование Set end)

                //  *** End programmer edit section *** (Контрагент.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        //  *** Start programmer edit section *** (Контрагент.ИНН CustomAttributes)

        //  *** End programmer edit section *** (Контрагент.ИНН CustomAttributes)
        [StrLen(255)]
        public virtual string ИНН
        {
            get
            {
                //  *** Start programmer edit section *** (Контрагент.ИНН Get start)

                //  *** End programmer edit section *** (Контрагент.ИНН Get start)
                string result = this.fИНН;
                //  *** Start programmer edit section *** (Контрагент.ИНН Get end)

                //  *** End programmer edit section *** (Контрагент.ИНН Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Контрагент.ИНН Set start)

                //  *** End programmer edit section *** (Контрагент.ИНН Set start)
                this.fИНН = value;
                //  *** Start programmer edit section *** (Контрагент.ИНН Set end)

                //  *** End programmer edit section *** (Контрагент.ИНН Set end)
            }
        }
        
        /// <summary>
        /// ОГРН.
        /// </summary>
        //  *** Start programmer edit section *** (Контрагент.ОГРН CustomAttributes)

        //  *** End programmer edit section *** (Контрагент.ОГРН CustomAttributes)
        [StrLen(255)]
        public virtual string ОГРН
        {
            get
            {
                //  *** Start programmer edit section *** (Контрагент.ОГРН Get start)

                //  *** End programmer edit section *** (Контрагент.ОГРН Get start)
                string result = this.fОГРН;
                //  *** Start programmer edit section *** (Контрагент.ОГРН Get end)

                //  *** End programmer edit section *** (Контрагент.ОГРН Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Контрагент.ОГРН Set start)

                //  *** End programmer edit section *** (Контрагент.ОГРН Set start)
                this.fОГРН = value;
                //  *** Start programmer edit section *** (Контрагент.ОГРН Set end)

                //  *** End programmer edit section *** (Контрагент.ОГРН Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтрагентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентE", typeof(IIS.project2.Контрагент));
                }
            }
            
            /// <summary>
            /// "КонтрагентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентL", typeof(IIS.project2.Контрагент));
                }
            }
        }
    }
}
