//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Начисления.
    /// </summary>
    //  *** Start programmer edit section *** (Начисления CustomAttributes)

    //  *** End programmer edit section *** (Начисления CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НачисленияE", new string[0])]
    [View("НачисленияL", new string[0])]
    public class Начисления : ICSSoft.STORMNET.DataObject
    {
        
        private System.Guid fprimarykey;
        
        private string fПериод;
        
        private decimal fСумма;
        
        private IIS.project2.Договор fДоговор;
        
        //  *** Start programmer edit section *** (Начисления CustomMembers)

        //  *** End programmer edit section *** (Начисления CustomMembers)

        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (Начисления.primarykey CustomAttributes)

        //  *** End programmer edit section *** (Начисления.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (Начисления.primarykey Get start)

                //  *** End programmer edit section *** (Начисления.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (Начисления.primarykey Get end)

                //  *** End programmer edit section *** (Начисления.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Начисления.primarykey Set start)

                //  *** End programmer edit section *** (Начисления.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (Начисления.primarykey Set end)

                //  *** End programmer edit section *** (Начисления.primarykey Set end)
            }
        }
        
        /// <summary>
        /// Период.
        /// </summary>
        //  *** Start programmer edit section *** (Начисления.Период CustomAttributes)

        //  *** End programmer edit section *** (Начисления.Период CustomAttributes)
        [StrLen(255)]
        public virtual string Период
        {
            get
            {
                //  *** Start programmer edit section *** (Начисления.Период Get start)

                //  *** End programmer edit section *** (Начисления.Период Get start)
                string result = this.fПериод;
                //  *** Start programmer edit section *** (Начисления.Период Get end)

                //  *** End programmer edit section *** (Начисления.Период Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Начисления.Период Set start)

                //  *** End programmer edit section *** (Начисления.Период Set start)
                this.fПериод = value;
                //  *** Start programmer edit section *** (Начисления.Период Set end)

                //  *** End programmer edit section *** (Начисления.Период Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        //  *** Start programmer edit section *** (Начисления.Сумма CustomAttributes)

        //  *** End programmer edit section *** (Начисления.Сумма CustomAttributes)
        public virtual decimal Сумма
        {
            get
            {
                //  *** Start programmer edit section *** (Начисления.Сумма Get start)

                //  *** End programmer edit section *** (Начисления.Сумма Get start)
                decimal result = this.fСумма;
                //  *** Start programmer edit section *** (Начисления.Сумма Get end)

                //  *** End programmer edit section *** (Начисления.Сумма Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Начисления.Сумма Set start)

                //  *** End programmer edit section *** (Начисления.Сумма Set start)
                this.fСумма = value;
                //  *** Start programmer edit section *** (Начисления.Сумма Set end)

                //  *** End programmer edit section *** (Начисления.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Начисления.
        /// </summary>
        //  *** Start programmer edit section *** (Начисления.Договор CustomAttributes)

        //  *** End programmer edit section *** (Начисления.Договор CustomAttributes)
        [NotNull()]
        public virtual IIS.project2.Договор Договор
        {
            get
            {
                //  *** Start programmer edit section *** (Начисления.Договор Get start)

                //  *** End programmer edit section *** (Начисления.Договор Get start)
                IIS.project2.Договор result = this.fДоговор;
                //  *** Start programmer edit section *** (Начисления.Договор Get end)

                //  *** End programmer edit section *** (Начисления.Договор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Начисления.Договор Set start)

                //  *** End programmer edit section *** (Начисления.Договор Set start)
                this.fДоговор = value;
                //  *** Start programmer edit section *** (Начисления.Договор Set end)

                //  *** End programmer edit section *** (Начисления.Договор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НачисленияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НачисленияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НачисленияE", typeof(IIS.project2.Начисления));
                }
            }
            
            /// <summary>
            /// "НачисленияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НачисленияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НачисленияL", typeof(IIS.project2.Начисления));
                }
            }
        }
    }
}
