//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.project2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплаты.
    /// </summary>
    //  *** Start programmer edit section *** (Оплаты CustomAttributes)

    //  *** End programmer edit section *** (Оплаты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатыE", new string[0])]
    [View("ОплатыL", new string[0])]
    public class Оплаты : ICSSoft.STORMNET.DataObject
    {
        
        private System.Guid fprimarykey;
        
        private System.DateTime fДата;
        
        private decimal fСумма;
        
        private IIS.project2.Договор fДоговор;
        
        //  *** Start programmer edit section *** (Оплаты CustomMembers)

        //  *** End programmer edit section *** (Оплаты CustomMembers)

        
        /// <summary>
        /// primarykey.
        /// </summary>
        //  *** Start programmer edit section *** (Оплаты.primarykey CustomAttributes)

        //  *** End programmer edit section *** (Оплаты.primarykey CustomAttributes)
        public virtual System.Guid primarykey
        {
            get
            {
                //  *** Start programmer edit section *** (Оплаты.primarykey Get start)

                //  *** End programmer edit section *** (Оплаты.primarykey Get start)
                System.Guid result = this.fprimarykey;
                //  *** Start programmer edit section *** (Оплаты.primarykey Get end)

                //  *** End programmer edit section *** (Оплаты.primarykey Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Оплаты.primarykey Set start)

                //  *** End programmer edit section *** (Оплаты.primarykey Set start)
                this.fprimarykey = value;
                //  *** Start programmer edit section *** (Оплаты.primarykey Set end)

                //  *** End programmer edit section *** (Оплаты.primarykey Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Оплаты.Дата CustomAttributes)

        //  *** End programmer edit section *** (Оплаты.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (Оплаты.Дата Get start)

                //  *** End programmer edit section *** (Оплаты.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (Оплаты.Дата Get end)

                //  *** End programmer edit section *** (Оплаты.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Оплаты.Дата Set start)

                //  *** End programmer edit section *** (Оплаты.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (Оплаты.Дата Set end)

                //  *** End programmer edit section *** (Оплаты.Дата Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        //  *** Start programmer edit section *** (Оплаты.Сумма CustomAttributes)

        //  *** End programmer edit section *** (Оплаты.Сумма CustomAttributes)
        public virtual decimal Сумма
        {
            get
            {
                //  *** Start programmer edit section *** (Оплаты.Сумма Get start)

                //  *** End programmer edit section *** (Оплаты.Сумма Get start)
                decimal result = this.fСумма;
                //  *** Start programmer edit section *** (Оплаты.Сумма Get end)

                //  *** End programmer edit section *** (Оплаты.Сумма Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Оплаты.Сумма Set start)

                //  *** End programmer edit section *** (Оплаты.Сумма Set start)
                this.fСумма = value;
                //  *** Start programmer edit section *** (Оплаты.Сумма Set end)

                //  *** End programmer edit section *** (Оплаты.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Оплаты.
        /// </summary>
        //  *** Start programmer edit section *** (Оплаты.Договор CustomAttributes)

        //  *** End programmer edit section *** (Оплаты.Договор CustomAttributes)
        [NotNull()]
        public virtual IIS.project2.Договор Договор
        {
            get
            {
                //  *** Start programmer edit section *** (Оплаты.Договор Get start)

                //  *** End programmer edit section *** (Оплаты.Договор Get start)
                IIS.project2.Договор result = this.fДоговор;
                //  *** Start programmer edit section *** (Оплаты.Договор Get end)

                //  *** End programmer edit section *** (Оплаты.Договор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Оплаты.Договор Set start)

                //  *** End programmer edit section *** (Оплаты.Договор Set start)
                this.fДоговор = value;
                //  *** Start programmer edit section *** (Оплаты.Договор Set end)

                //  *** End programmer edit section *** (Оплаты.Договор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатыE", typeof(IIS.project2.Оплаты));
                }
            }
            
            /// <summary>
            /// "ОплатыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатыL", typeof(IIS.project2.Оплаты));
                }
            }
        }
    }
}
